import { mkdir, writeFile } from "node:fs/promises";
import { relative, resolve } from "node:path";
import type { CompileOptions } from "@nitrofoundation/nitrocss/compiler";
import { compile, scanCandidates } from "../compiler";

export const AUTOCOMPLETE_SCHEMA_VERSION = 1 as const;

export interface AutocompleteManifest {
  schemaVersion: typeof AUTOCOMPLETE_SCHEMA_VERSION;
  generatedAt: string;
  input: string;
  classes: string[];
}

export interface GenerateAutocompleteOptions extends CompileOptions {
  /** Output directory. Defaults to `.nitrowind` under cwd. */
  outDir?: string;
  /** Used by deterministic tooling/tests. */
  now?: () => Date;
}

export interface GenerateAutocompleteResult {
  manifest: AutocompleteManifest;
  manifestPath: string;
  typesPath: string;
}

const quoteType = (value: string): string => JSON.stringify(value);

export function renderAutocompleteTypes(classes: readonly string[]): string {
  const union = classes.length > 0 ? classes.map(quoteType).join(" | ") : "never";
  return [
    "// Generated by `nitrowind autocomplete`. Do not edit.",
    `export type NitroWindClassName = ${union};`,
    "export type NitroWindClassList =",
    "  | NitroWindClassName",
    "  | `${NitroWindClassName} ${string}`",
    "  | (string & {});",
    "",
  ].join("\n");
}

/**
 * Scan the app and compile its CSS, then write only candidates that produced a
 * NitroWind class. JSON is intended for editor integrations; the declaration
 * provides a local union type for component libraries and design-system APIs.
 */
export async function generateAutocomplete(
  options: GenerateAutocompleteOptions,
): Promise<GenerateAutocompleteResult> {
  const cwd = resolve(options.cwd ?? process.cwd());
  const candidates = scanCandidates({ ...options, cwd });
  const artifact = await compile({ ...options, cwd });
  const compiled = new Set(Object.keys(artifact.classes));
  const classes = candidates.filter((candidate) => compiled.has(candidate)).sort();
  const outDir = resolve(cwd, options.outDir ?? ".nitrowind");
  const manifestPath = resolve(outDir, "classes.json");
  const typesPath = resolve(outDir, "classes.d.ts");
  const manifest: AutocompleteManifest = {
    schemaVersion: AUTOCOMPLETE_SCHEMA_VERSION,
    generatedAt: (options.now ?? (() => new Date()))().toISOString(),
    input: relative(cwd, resolve(cwd, options.input)) || options.input,
    classes,
  };

  await mkdir(outDir, { recursive: true });
  await Promise.all([
    writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8"),
    writeFile(typesPath, renderAutocompleteTypes(classes), "utf8"),
  ]);

  return { manifest, manifestPath, typesPath };
}
