/**
 * Reanimated preset tables.
 *
 * The build pipeline bakes animation *intent* into `--reanimated-*` custom
 * properties. The runtime (`src/core/reanimated.ts`) reads those properties
 * back and instantiates the matching Reanimated animation builder — the
 * JS/UI-thread path Reanimated requires. These tables are the canonical list
 * of preset names both sides agree on.
 */

/** Entering/exiting presets (each yields an `entering-*` and `exiting-*`). */
export const ENTERING_EXITING_PRESETS = [
  "BounceIn",
  "BounceInDown",
  "BounceInLeft",
  "BounceInRight",
  "BounceInUp",
  "BounceOut",
  "BounceOutDown",
  "BounceOutLeft",
  "BounceOutRight",
  "BounceOutUp",
  "FadeIn",
  "FadeInDown",
  "FadeInLeft",
  "FadeInRight",
  "FadeInUp",
  "FadeOut",
  "FadeOutDown",
  "FadeOutLeft",
  "FadeOutRight",
  "FadeOutUp",
  "FlipInEasyX",
  "FlipInEasyY",
  "FlipInXDown",
  "FlipInXUp",
  "FlipInYLeft",
  "FlipInYRight",
  "FlipOutEasyX",
  "FlipOutEasyY",
  "FlipOutXDown",
  "FlipOutXUp",
  "FlipOutYLeft",
  "FlipOutYRight",
  "LightSpeedInLeft",
  "LightSpeedInRight",
  "LightSpeedOutLeft",
  "LightSpeedOutRight",
  "PinwheelIn",
  "PinwheelOut",
  "RollInLeft",
  "RollInRight",
  "RollOutLeft",
  "RollOutRight",
  "RotateInDownLeft",
  "RotateInDownRight",
  "RotateInUpLeft",
  "RotateInUpRight",
  "RotateOutDownLeft",
  "RotateOutDownRight",
  "RotateOutUpLeft",
  "RotateOutUpRight",
  "SlideInDown",
  "SlideInLeft",
  "SlideInRight",
  "SlideInUp",
  "SlideOutDown",
  "SlideOutLeft",
  "SlideOutRight",
  "SlideOutUp",
  "StretchInX",
  "StretchInY",
  "StretchOutX",
  "StretchOutY",
  "ZoomIn",
  "ZoomInDown",
  "ZoomInEasyDown",
  "ZoomInEasyUp",
  "ZoomInLeft",
  "ZoomInRight",
  "ZoomInRotate",
  "ZoomInUp",
  "ZoomOut",
  "ZoomOutDown",
  "ZoomOutEasyDown",
  "ZoomOutEasyUp",
  "ZoomOutLeft",
  "ZoomOutRight",
  "ZoomOutRotate",
  "ZoomOutUp",
] as const;

/** Layout-transition presets (each yields a `layout-*`). */
export const LAYOUT_PRESETS = [
  "CurvedTransition",
  "EntryExitTransition",
  "SequencedTransition",
  "LinearTransition",
  "JumpingTransition",
  "FadingTransition",
] as const;
